### ISSUE TITLE
docker-compose 跑起来证书申请没任何反应 

### ISSUE THREAD

**Issue by hale177** [nekoimi/oss-auto-cert#13]
我这边 oss bucket 绑定是原来在阿里云官方购买的证书 ，9月17 到期 ，
我在 config.yaml 配置 expired-early 是 30 天 ，但是 compose 起来后，没任何反应和申请证书的动作 

**环境配置信息如下（关键配置做了隐藏处理）**

config.yaml 
```
# 企业微信机器人webhook地址
webhook: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxx-xxxxx-xxxxx-xxxxxx-xxxxxxx
# 证书申请配置
acme:
  email: 111@qq.com
  data-dir: /ssldata
  expired-early: 30 
# 阿里云OSS配置 Bucket信息列表
buckets:
  - name: sit-aa-bb
    endpoint: sit-aa-bb.oss-cn-shanghai.aliyuncs.com
```

docker-compose.yaml 
```
version: "3.8"
services:
  oss-auto-cert:
    image: nekoimi/oss-auto-cert:latest
    container_name: oss-auto-cert
    hostname: oss-auto-cert
    network_mode: host
    command:
      - -log-level=debug
    volumes:
      - ./etc/config.yaml:/etc/oss-auto-cert/config.yaml
      - ./data:/ssldata
    privileged: true
    restart: unless-stopped
    environment:
      OSS_ACCESS_KEY_ID: aaa
      OSS_ACCESS_KEY_SECRET: bbbb
      ACME_EMAIL: 111@qq.com
      ACME_DATA_DIR: /ssldata
      ACME_EXPIRED_EARLY: 30
```

 docker-compose logs -f  日志:
```
oss-auto-cert  | 2024/08/25 01:00:00 DEBU <config/config.go:76> 配置文件: &{/etc/oss-auto-cert/config.yaml https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxx-xxxxx-xxxxx-xxxxxx-xxxxxxx {111@qq.com /ssldata %!s(int=30)} [{sit-aa-bb sit-aa-bb.oss-cn-shanghai.aliyuncs.com}]}
oss-auto-cert  | 2024/08/25 01:00:00 DEBU <config/config.go:83> set acme (email) from env: 111@qq.com
oss-auto-cert  | 2024/08/25 01:00:00 DEBU <config/config.go:89> set acme (data dir) from env: /ssldata
oss-auto-cert  | 2024/08/25 01:00:00 DEBU <config/config.go:98> set acme (expired early) from env: 30
oss-auto-cert  | 2024/08/25 01:00:00 DEBU <config/config.go:103> 配置文件: &{/etc/oss-auto-cert/config.yaml https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxxxx-xxxxx-xxxxx-xxxxxx-xxxxxxx {111@qq.com /ssldata %!s(int=30)} [{sit-aa-bb sit-aa-bb.oss-cn-shanghai.aliyuncs.com}]}
oss-auto-cert  | 2024/08/25 01:00:00 INFO <acme/lego.go:46> Lego CA-Dir use production
oss-auto-cert  | 2024/08/25 01:00:01 [INFO] acme: Registering account for 111@qq.com

```
